import test from 'node:test';import assert from 'node:assert/strict';
import {accountGardenJournal} from '../src/lib/garden/accountGardenJournal.js';
const workspace=(id)=>({id,name:id,property:{id},beds:[{id:'b',name:'Bed'}],structures:[],vegetation:[],placements:[{id:'p',plantId:'tomato',bedId:'b',planted:'2026-05-20'}]});
const record=()=>{const a=workspace('a'),b=workspace('b');return {id:'save',name:'Account garden',revision:'"r1"',payload:{...a,activeParcelId:'a',parcels:[a,b],plants:[{id:'tomato'}],layouts:[]}};};
const event={type:'watering',date:'2026-06-01'};
test('logs to explicitly selected garden and preserves the other garden and active mirror',async()=>{let saved;const session=accountGardenJournal({owner:()=> 'owner',client:{load:async()=>record(),update:async(id,revision,name,payload)=>{saved={id,revision,name,payload};return {revision:'"r2"'};}}});await session.load('save');session.select('b');await session.log('p',event);assert.equal(saved.revision,'"r1"');assert.equal(saved.payload.placements[0].observations,undefined);assert.equal(saved.payload.parcels.find(g=>g.id==='b').placements[0].observations.length,1);assert.equal(session.workspace().placements[0].observations.length,1);});
test('conflict does not change local history and refuses retry until reloaded',async()=>{let calls=0;const session=accountGardenJournal({owner:()=> 'owner',client:{load:async()=>record(),update:async()=>{calls++;throw Object.assign(Error('conflict'),{code:'revision_conflict'});}}});await session.load('save');session.select('a');await assert.rejects(session.log('p',event),/not saved/);assert.equal(session.workspace().placements[0].observations,undefined);await assert.rejects(session.log('p',event),/Reload/);assert.equal(calls,1);});
test('owner change discards loaded data and rejects a delayed response',async()=>{let owner='one',resolve;const session=accountGardenJournal({owner:()=>owner,client:{load:()=>new Promise(r=>resolve=r)}});const loading=session.load('save');owner='two';resolve(record());await assert.rejects(loading,/account changed/);assert.throws(()=>session.workspace(),/account changed/);});
test('only one save is in flight and external callers cannot mutate cached records',async()=>{let resolve;const session=accountGardenJournal({owner:()=> 'owner',client:{load:async()=>record(),update:()=>new Promise(r=>resolve=r)}});await session.load('save');session.select('a');session.workspace().placements.pop();assert.equal(session.workspace().placements.length,1);const first=session.log('p',event);await assert.rejects(session.log('p',event),/already saving/);resolve({revision:'"r2"'});await first;assert.equal(session.workspace().placements[0].observations.length,1);});
