import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createAccountSandbox,DEMO_LIMITS} from '../src/lib/demo/sandbox.js';
const fixture=JSON.parse(fs.readFileSync(new URL('../data/demo/community-garden.json',import.meta.url)));
function demo(overrides={}){let time=1000000,ids=0;return {sandbox:createAccountSandbox({now:()=>time,id:()=>`00000000-0000-4000-8000-${String(++ids).padStart(12,'0')}`,limits:{...DEMO_LIMITS,...overrides}}),tick:()=>time+=300,expire:()=>time+=DEMO_LIMITS.lifetimeMs+1};}
test('sandbox isolates users, preserves versions and rejects stale revisions without remote writes',async()=>{
 const a=demo(),b=demo();const originalFetch=globalThis.fetch;globalThis.fetch=()=>{throw Error('Sandbox must not call fetch');};
 try{const saved=await a.sandbox.client.create('Example',fixture);a.tick();const changed=structuredClone(fixture);changed.beds[0].name='Changed';const updated=await a.sandbox.client.update(saved.id,saved.revision,'Example',changed);a.tick();await assert.rejects(a.sandbox.client.update(saved.id,saved.revision,'Stale',fixture),{code:'revision_conflict'});a.tick();const earlier=await a.sandbox.client.load(saved.id,saved.revision);assert.equal(earlier.payload.beds[0].name,fixture.beds[0].name);assert.notEqual(updated.revision,saved.revision);assert.deepEqual((await b.sandbox.client.list()).plans,[]);}finally{globalThis.fetch=originalFetch;}
});
test('sandbox expires, clears drafts and refuses writes after closing',async()=>{const d=demo();d.sandbox.storage.setItem('draft','private demo');d.expire();assert.throws(()=>d.sandbox.storage.getItem('draft'),{code:'demo_expired'});assert.equal(d.sandbox.stats().plans,0);assert.equal(d.sandbox.session(),null);await assert.rejects(d.sandbox.client.create('late',fixture),{code:'demo_expired'});});
test('account operation rate, count and plan limits are enforced',async()=>{const d=demo({maxOperations:3,maxPlans:1});await d.sandbox.client.create('one',fixture);await assert.rejects(d.sandbox.client.list(),{code:'demo_rate_limit'});d.tick();await assert.rejects(d.sandbox.client.create('two',fixture),{code:'demo_limit'});d.tick();await d.sandbox.client.list();d.tick();await assert.rejects(d.sandbox.client.list(),{code:'demo_limit'});});
test('oversized data rolls back atomically; notebook drafts share the same bound',async()=>{const d=demo({maxBytes:200});await assert.rejects(d.sandbox.client.create('too big',fixture),{code:'save_too_large'});assert.equal(d.sandbox.stats().plans,0);d.sandbox.storage.setItem('draft','keep');assert.throws(()=>d.sandbox.storage.setItem('draft','x'.repeat(201)),{code:'save_too_large'});assert.equal(d.sandbox.storage.getItem('draft'),'keep');});
test('version history is bounded and returned values cannot mutate storage',async()=>{const d=demo({maxVersions:2});let saved=await d.sandbox.client.create('one',fixture);for(let i=0;i<4;i++){d.tick();saved=await d.sandbox.client.update(saved.id,saved.revision,'one',fixture);}d.tick();assert.equal((await d.sandbox.client.history(saved.id)).versions.length,2);d.tick();const value=await d.sandbox.client.load(saved.id);value.name='injected';d.tick();assert.equal((await d.sandbox.client.load(saved.id)).name,'one');});
