import test from 'node:test';import assert from 'node:assert/strict';
import {planNextSeason,shiftPlanYear,seasonPlantings,seasonPreviewDate} from '../src/lib/garden/nextSeason.js';
const garden=()=>({id:'garden',property:{gardenContext:{sunHours:6}},beds:[{id:'bed',width:48,height:96}],siteFeatures:[{id:'path',points:[[1,2],[3,4]]}],placements:[{id:'tomato-2026',plantId:'tomato',bedId:'bed',x:24,y:30,planted:'2026-05-20',plannedUntil:'2026-10-01',observations:[{plantingId:'tomato-2026',type:'harvested',date:'2026-08-01',quantity:4,unit:'lb'}],harvestEstimate:{reference:'packet'},sizeScenario:{height:12}},{id:'berry',plantId:'blueberry',bedId:'bed',x:20,y:70,planted:'2025-05-01',plannedUntil:'2026-12-31',observations:[]}]});
const options={fromYear:2026,toYear:2027,choices:[{id:'tomato-2026',action:'repeat',sourceEnd:'2026-10-01',start:'2027-05-20',end:'2027-10-01'},{id:'berry',action:'retain'}]};
test('next year keeps infrastructure and original history while repeating annuals with independent identities',()=>{const w=garden(),before=structuredClone(w),next=planNextSeason(w,options,()=> 'tomato-2027');assert.deepEqual(w,before);assert.deepEqual(next.beds,w.beds);assert.deepEqual(next.siteFeatures,w.siteFeatures);assert.deepEqual(next.property.gardenContext,w.property.gardenContext);assert.deepEqual(next.placements[0],w.placements[0]);assert.equal(next.placements[1].id,'berry');assert.equal(next.placements[1].plannedUntil,'');const copy=next.placements[2];assert.equal(copy.previousSeasonPlantingId,'tomato-2026');assert.equal(copy.planted,'2027-05-20');assert.equal(copy.x,24);for(const key of ['observations','harvestEstimate','sizeScenario'])assert.equal(copy[key],undefined);assert.deepEqual(next.property.seasonPlans[0].continuingPlantingIds,['berry']);assert.throws(()=>planNextSeason(next,options),/already/);});
test('selection is explicit and planning an empty season does not remove previous plants',()=>{const w=garden(),next=planNextSeason(w,{...options,choices:[]});assert.deepEqual(next.placements,w.placements);assert.equal(next.property.seasonPlans[0].plantingIds.length,0);});
test('invalid dates, overlap, foreign IDs and finished perennials are rejected without mutation',()=>{for(const changes of [{start:'2027-02-30'},{end:''},{sourceEnd:'2027-05-21'},{id:'foreign'}]){const w=garden();assert.throws(()=>planNextSeason(w,{...options,choices:[{...options.choices[0],...changes}]}));assert.deepEqual(w,garden());}const w=garden();w.placements[1].observations=[{plantingId:'berry',type:'ended',date:'2026-10-01'}];assert.throws(()=>planNextSeason(w,options),/finished/);assert.throws(()=>planNextSeason(garden(),options,()=> 'berry'),/unique/);});
test('date suggestions clamp leap day and season candidates include undated records for explicit review',()=>{assert.equal(shiftPlanYear('2028-02-29',1),'2029-02-28');assert.equal(shiftPlanYear('',1),'');const w=garden();w.placements.push({id:'future',planted:'2028-05-01'},{id:'unknown'},{id:'old',plannedUntil:'2024-09-01'});assert.deepEqual(seasonPlantings(w,2026).map(p=>p.id),['tomato-2026','berry','unknown']);});

test('season navigation opens the earliest dated planting without changing the garden',()=>{const w=garden(),before=structuredClone(w);assert.equal(seasonPreviewDate(w,2026),'2026-05-20');assert.equal(seasonPreviewDate(w,2027),'2027-01-01');assert.throws(()=>seasonPreviewDate(w,NaN));assert.deepEqual(w,before);});
