import test from 'node:test';import assert from 'node:assert/strict';
import {observationPhoto,MAX_OBSERVATION_PHOTO_BYTES} from '../src/lib/garden/observationPhoto.js';
import {recordPlantingObservation,gardenJourney} from '../src/lib/garden/plantingJournal.js';
import {parsePlannerBackup} from '../src/lib/garden/plannerBackup.js';
import {accountGardenPayload} from '../src/lib/garden/accountGardens.js';
const photo={version:1,width:1,height:1,dataUrl:'data:image/jpeg;base64,/9j/2Q=='};
test('photo-only observations keep stable identity and survive account backup round trip',()=>{const original={id:'p',plantId:'tomato',bedId:'b',planted:'2026-05-01'},planting=recordPlantingObservation(original,{type:'note',date:'2026-06-01',photo:{...photo,filename:'private.jpg',gps:'private'}});const g={id:'g',property:{},beds:[{id:'b'}],structures:[],vegetation:[],placements:[planting]};const saved=accountGardenPayload(parsePlannerBackup(JSON.stringify({...g,parcels:[g],activeParcelId:'g',plants:[],layouts:[]})));const event=gardenJourney(saved.parcels[0],2026).events[0];assert.deepEqual(event.photo,photo);assert.equal(event.plantingId,'p');assert.equal(saved.placements[0].planted,original.planted);assert.equal(original.observations,undefined);});
test('reject external, vector, excessive and invalid image records',()=>{for(const invalid of [{...photo,dataUrl:'https://example.com/private.jpg'},{...photo,dataUrl:'data:image/svg+xml;base64,PHN2Zz4='},{...photo,width:0},{...photo,height:961},{...photo,dataUrl:'data:image/jpeg;base64,/9j/'+ 'A'.repeat(MAX_OBSERVATION_PHOTO_BYTES*2)},{...photo,version:2}])assert.throws(()=>observationPhoto(invalid));assert.equal(observationPhoto(null),null);});
test('bad photo refuses observation instead of silently dropping attachment',()=>{assert.throws(()=>recordPlantingObservation({id:'p'},{type:'note',date:'2026-06-01',notes:'hello',photo:{}}));assert.throws(()=>recordPlantingObservation({id:'p'},{type:'note',date:'2026-06-01'}));});
