import test from 'node:test';import assert from 'node:assert/strict';
import {plantIntent,plantPlanUrl,readPlantIntent,plannedCatalogPlant,addPlanningTrayEntry} from '../src/lib/garden/plantIntent.js';
import {accountGardenPayload} from '../src/lib/garden/accountGardens.js';
const record={id:'plant:catalog:cherokee-purple',name:'Tomato — Cherokee Purple',common:'Tomato',cultivar:'Cherokee Purple',scientific:'Solanum lycopersicum',source:'https://example.org/tomato',spacingMax:30};
test('public catalog handoff retains cultivar identity and excludes private/untrusted fields',()=>{const url=new URL(plantPlanUrl({...record,privateGarden:'secret',password:'no'}));assert.equal(url.search,'');assert.deepEqual(readPlantIntent(url.hash),plantIntent(record));assert.ok(!url.href.includes('secret'));assert.equal(plantIntent({...record,source:'javascript:alert(1)'}).source,'');assert.equal(readPlantIntent('#my-gardens'),null);assert.throws(()=>readPlantIntent('#plant='+'a'.repeat(10000)));});
test('tray isolates destination, preserves choices and survives account projection',()=>{
 const garden=id=>({id,name:id,property:{id},beds:[{id:id+'-bed'}],structures:[],vegetation:[],placements:[]});const state={activeParcelId:'one',parcels:[garden('one'),garden('two')],plants:[],layouts:[]};
 const plant=plannedCatalogPlant(record,{spacing:30,diameter:28,height:60},'chosen');const before=JSON.stringify(state.parcels[0]);const entry=addPlanningTrayEntry(state,{gardenId:'two',bedId:'two-bed',year:2027,plant},()=> 'choice');assert.equal(JSON.stringify(state.parcels[0]),before);assert.equal(state.parcels[1].placements.length,0);assert.equal(state.plants[0].catalogIdentity.cultivar,'Cherokee Purple');assert.equal(addPlanningTrayEntry(state,{gardenId:'two',bedId:'two-bed',year:2027,plant},()=> 'duplicate'),entry);assert.equal(state.plants.length,1);
 const account=accountGardenPayload(state);assert.equal(account.parcels[1].property.planningTray[0].year,2027);assert.equal(account.plants[0].catalogIdentity.id,record.id);
 assert.throws(()=>addPlanningTrayEntry(state,{gardenId:'one',bedId:'two-bed',year:2027,plant}));assert.throws(()=>plannedCatalogPlant(record,{spacing:0,diameter:28,height:60},'bad'));
});
test('Today crop intent carries a planned date without inventing a cultivar or private destination',async()=>{const {cropPlanUrl}=await import('../src/lib/garden/plantIntent.js');const url=new URL(cropPlanUrl({slug:'tomatoes',name:'Tomatoes',privateGarden:'hidden'},'2027-05-21'));const intent=readPlantIntent(url.hash);assert.equal(intent.id,'guide:tomatoes');assert.equal(intent.cultivar,'');assert.equal(intent.plannedDate,'2027-05-21');assert.equal(intent.spacingMax,null);assert.ok(!url.href.includes('hidden'));assert.throws(()=>cropPlanUrl({slug:'tomatoes',name:'Tomatoes'},'2027-02-30'));const plant=plannedCatalogPlant(intent,{spacing:30,diameter:24,height:60},'new');assert.equal(plant.planningDate,'2027-05-21');});
test('dated tray choices remain distinct for succession and reject conflicting years',()=>{const state={parcels:[{id:'g',property:{},beds:[{id:'b'}]}],plants:[]};const make=(id,date)=>plannedCatalogPlant({...record,plannedDate:date},{spacing:30,diameter:24,height:60},id);addPlanningTrayEntry(state,{gardenId:'g',bedId:'b',year:2027,plannedDate:'2027-05-21',plant:make('one','2027-05-21')},()=> 'one');addPlanningTrayEntry(state,{gardenId:'g',bedId:'b',year:2027,plannedDate:'2027-08-01',plant:make('two','2027-08-01')},()=> 'two');assert.equal(state.parcels[0].property.planningTray.length,2);assert.throws(()=>addPlanningTrayEntry(state,{gardenId:'g',bedId:'b',year:2026,plannedDate:'2027-05-21',plant:make('bad','2027-05-21')}));});

test('Today combines crop/date with exact saved garden/bed without leaking contents',async()=>{const {cropPlanUrl}=await import('../src/lib/garden/plantIntent.js');const {readGardenHandoff}=await import('../src/lib/garden/gardenHandoff.js');const destination={saveId:'12345678-1234-1234-1234-123456789abc',gardenId:'South',bedId:'bed-2'};const url=new URL(cropPlanUrl({slug:'tomatoes',name:'Tomatoes'},'2027-05-21','https://studio.veggie.farm/',{...destination,notes:'private contents',token:'secret'}));assert.deepEqual(readGardenHandoff(url.hash),destination);assert.equal(readPlantIntent(url.hash).plannedDate,'2027-05-21');assert.ok(!url.href.includes('secret'));assert.ok(!url.href.includes('private'));assert.equal(url.search,'');assert.throws(()=>cropPlanUrl({slug:'tomatoes',name:'Tomatoes'},'2027-05-21',url.origin,{saveId:'invalid'}));});
