import {soilReadingContext} from '../lib/garden/soilReading.js';
import {loadGardenProfile,profileDatesForYear} from '../lib/garden/localGardenStore.js';
import {gardenSnapshot,localDay} from '../lib/garden/gardenRecords.js';
import {recommendGardenToday} from '../lib/recommendations/gardenToday.js';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;};
export function cropStatus(crop,rules,evidence,{invalidation}={}){const root=el('aside');root.className='today-input-note';const render=()=>{root.replaceChildren();const profile=loadGardenProfile(),date=localDay(),year=Number(date.slice(0,4));const frost=profileDatesForYear(profile||{},year);const days=Math.round((new Date(`${frost.firstFrostDate}T12:00:00`)-new Date(`${date}T12:00:00`))/86400000);root.append(el('strong',`${crop.name} in your season`));const tracked=gardenSnapshot().plantings.filter(p=>p.crop.toLowerCase()===crop.name.toLowerCase()||p.cropSlug===crop.slug);if(tracked.length)root.append(el('p',tracked.map(p=>`${p.bed}: ${p.stage}`).join(' · ')));
const reading=soilReadingContext(profile,date);
if(reading.status==='today'&&rules.length){const result=recommendGardenToday([crop],rules,{date,...frost,soilTemperatureF:profile.soilTemperatureF,riskPreference:'typical',forecast:null},evidence)[0];if(result)root.append(el('p',result.explanation[0]));root.append(el('p',`Uses the saved ${profile.soilTemperatureF}°F soil reading measured ${reading.date}; remeasure before acting. No current forecast loaded.`));}
else {if(reading.value!=null)root.append(el('p',`Saved soil reading: ${reading.value}°F · ${reading.date || 'date not recorded'}. ${reading.status==='future'?'The date is in the future. ':''}Enter a current measurement in Garden Today before using it for planting.`));root.append(el('p',`Current soil warmth is not recorded. ${days>=0?`${days} days remain before`:`The entered frost date is ${Math.abs(days)} days ago:`} ${frost.firstFrostDate}. A frost date is a planning estimate, not a forecast.`));}
root.append(el('p',profile?'Using frost dates from your saved garden profile.':'Example frost dates: May 10 and October 15. Enter your own dates before deciding.'));const a=el('a','Check today’s timing and change these assumptions →');a.href='/tools/today';root.append(a);};render();for(const event of ['garden-records-changed','notebook-sync-status','focus'])globalThis.addEventListener(event,render);invalidation?.then(()=>{for(const event of ['garden-records-changed','notebook-sync-status','focus'])globalThis.removeEventListener(event,render);});return root;}
