import {lookupMappedSoil} from '../lib/environment/mappedSoil.js';
const el=(tag,text)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;};
export function mappedSoil({getLocation,onBoundary=()=>{},invalidation}={}){
 const root=el('details');root.className='mapped-soil-context';root.append(el('summary','USDA mapped soil context'));root.append(el('p','A landscape estimate, not a soil test. Fill, compost and raised beds can differ from the mapped ground.'));
 const form=el('form');form.className='mapped-soil-form';root.append(form);function field(label){const wrap=el('label',label),input=el('input');input.type='number';input.step='any';input.required=true;input.setAttribute('aria-label',label);wrap.append(input);form.append(wrap);return input;}const lat=field('Soil lookup latitude'),lon=field('Soil lookup longitude');
 if(getLocation){const use=el('button','Use current garden origin');use.type='button';use.onclick=()=>{const p=getLocation();if(p){lon.value=p[0];lat.value=p[1];status.textContent='Coordinates filled. Choose Look up to send this point to USDA.';}};form.append(use);}
 form.append(el('p','Only when you choose Look up, these coordinates are sent directly to USDA. Results stay in this view; download the source record to keep a copy.'));
 const submit=el('button','Look up mapped soil');submit.type='submit';form.append(submit);const status=el('p');status.setAttribute('role','status');root.append(status);const output=el('div');root.append(output);let controller,result,downloadUrl;
 function clear(){controller?.abort();controller=null;result=null;output.replaceChildren();onBoundary([]);if(downloadUrl)URL.revokeObjectURL(downloadUrl);downloadUrl=null;}
 form.onsubmit=async event=>{event.preventDefault();clear();controller=new AbortController();const active=controller;submit.disabled=true;status.textContent='Loading USDA survey context…';try{const r=await lookupMappedSoil(lon.value,lat.value,{signal:AbortSignal.any([active.signal,AbortSignal.timeout(25000)])});if(controller!==active)return;result=r;status.textContent=r.components.length?'USDA mapped landscape estimate · not a soil test':'No mapped soil was returned at this point.';if(!r.components.length)return;
 const table=el('table'),head=el('tr');for(const label of ['Map unit','Component (% of unit)','Drainage','Representative slope','Survey version'])head.append(el('th',label));const thead=el('thead');thead.append(head);table.append(thead);const tbody=el('tbody');for(const c of r.components){const row=el('tr');for(const value of [`${c.musym} · ${c.muname}`,`${c.compname??'Not recorded'} (${c.comppct_r??'?'}%)`,c.drainagecl??'Not recorded',c.slope_r==null?'Not recorded':c.slope_r+'%',`${c.areasymbol} · ${c.saverest}`])row.append(el('td',value));tbody.append(row);}table.append(tbody);const scroll=el('div');scroll.className='mapped-soil-table';scroll.tabIndex=0;scroll.setAttribute('aria-label','Mapped soil component table');scroll.append(table);output.append(scroll,el('p','Component proportions apply to the map unit; they do not identify the component beneath your bed. Texture and available-water estimates are not included in this lookup.'));
 const check=el('input');check.type='checkbox';const label=el('label',' Show point-intersecting soil boundaries on the garden map');if(getLocation){label.prepend(check);output.append(label);check.onchange=()=>onBoundary(check.checked?r.boundaries:[]);}
 const evidence=el('details');evidence.append(el('summary','Source and limits'));evidence.append(el('p',`Retrieved ${r.retrievedAt}. Survey version is a dataset date, not a soil-sampling date. Up to 100 components and five polygons are returned; a point on a boundary can intersect multiple units.`));const source=el('a','USDA Soil Data Access');source.href='https://sdmdataaccess.nrcs.usda.gov/WebServiceHelp.aspx';evidence.append(source);downloadUrl=URL.createObjectURL(new Blob([JSON.stringify(r,null,2)],{type:'application/json'}));const download=el('a','Download source record (JSON)');download.href=downloadUrl;download.download='usda-mapped-soil.json';evidence.append(el('p'),download);output.append(evidence);
 }catch(e){if(controller===active)status.textContent=e.name==='AbortError'?'Lookup cancelled.':e.message;}finally{if(controller===active)submit.disabled=false;}};
 root.clear=()=>{clear();submit.disabled=false;status.textContent='Garden changed. Look up the new point to see its mapped soil.';lat.value='';lon.value='';};invalidation?.then(clear);return root;
}
