import {loadGardenJournal} from '../lib/garden/localGardenStore.js';
import {compareSeasonWeather} from '../lib/environment/seasonWeather.js';
function el(tag,text){const n=document.createElement(tag);if(text!=null)n.textContent=text;return n;}
function choice(parent,label,options,value){const l=el('label');l.append(el('span',label));const s=el('select');s.setAttribute('aria-label',label);options.forEach(([v,t])=>{const o=el('option',t);o.value=v;s.append(o);});s.value=value;l.append(s);parent.append(l);return s;}
function svgElement(tag,attributes={}){const n=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const [k,v] of Object.entries(attributes))n.setAttribute(k,v);return n;}
function chart(data,events=[],mode='daily'){
 const labels={daily:'Daily air-temperature midpoints in °F',departure:'Departure from 1991–2020 normal midpoint in °F',accumulated:'Month-to-date precipitation in inches; line ends at the first missing day'};
 const svg=svgElement('svg',{viewBox:'0 0 700 320',role:'img','aria-label':`${labels[mode]}. Exact values and coverage follow in the table.`});
 const series=mode==='daily'?[['current','var(--green)',''],['baseline','var(--soil)','6 4'],['normal','var(--muted)','2 4']]:mode==='departure'?[['departure','var(--green)','']]:[['rainAccumulated','var(--green)','']];
 const vals=data.rows.flatMap(d=>series.map(([key])=>d[key])).filter(Number.isFinite);
 if(!vals.length)return el('p','No observations available for this view and month. Missing data is not zero.');
 const floor=mode==='daily'?32:0,lo=Math.min(floor,...vals),hi=Math.max(mode==='daily'?42:1,...vals),pad=(hi-lo)*.08;
 const x=d=>50+(d-1)*625/(data.totalDays-1),y=v=>215-(v-(lo-pad))*185/(hi-lo+2*pad);
 for(let step=0;step<=4;step++){const v=lo+(hi-lo)*step/4;svg.append(svgElement('line',{x1:50,x2:680,y1:y(v),y2:y(v),stroke:'var(--line)'}));const t=svgElement('text',{x:43,y:y(v)+4,'text-anchor':'end',fill:'currentColor','font-size':12});t.textContent=mode==='accumulated'?v.toFixed(1):v.toFixed(0)+'°';svg.append(t);}
 if(mode!=='accumulated'){const threshold=mode==='daily'?32:0;svg.append(svgElement('line',{x1:50,x2:680,y1:y(threshold),y2:y(threshold),stroke:'currentColor','stroke-dasharray':'3 3'}));const text=svgElement('text',{x:54,y:y(threshold)-5,fill:'currentColor','font-size':11});text.textContent=mode==='daily'?'32°F freezing':'Normal midpoint';svg.append(text);}
 for(const [key,color,dash] of series){let path='',open=false;for(const d of data.rows){if(d[key]===null){open=false;continue;}path+=`${open?'L':'M'}${x(d.day)},${y(d[key])} `;open=true;}svg.append(svgElement('path',{d:path,fill:'none',stroke:color,'stroke-width':2.5,'stroke-dasharray':dash}));}
 for(const d of data.rows){if(d.low!==null&&d.low<=32){const mark=svgElement('path',{d:`M${x(d.day)},232 l-4,7 h8 z`,fill:'currentColor'});const title=svgElement('title');title.textContent=`${d.date}: station low ${d.low.toFixed(1)}°F`;mark.append(title);svg.append(mark);}}
 for(const event of events){const day=Number(event.date.slice(8,10)),mark=svgElement('circle',{cx:x(day),cy:251,r:4,fill:'var(--soil)'});const title=svgElement('title');title.textContent=`${event.date}: ${event.crop||'Garden'} — ${event.type.replaceAll('_',' ')}`;mark.append(title);svg.append(mark);}
 for(const [key,yPos,label] of [['current',271,'Temp'],['rain',288,'Rain']]){const title=svgElement('text',{x:3,y:yPos+8,fill:'currentColor','font-size':10});title.textContent=label;svg.append(title);for(const d of data.rows){const mark=svgElement('rect',{x:x(d.day)-4,y:yPos,width:8,height:9,fill:d[key]===null?'none':'var(--green)',stroke:'var(--muted)'});const tooltip=svgElement('title');tooltip.textContent=`${d.date}: ${label} ${d[key]===null?'missing':'recorded'}`;mark.append(tooltip);svg.append(mark);}}
 for(const day of [1,10,20,data.totalDays]){const t=svgElement('text',{x:x(day),y:315,'text-anchor':'middle',fill:'currentColor','font-size':12});t.textContent=day;svg.append(t);}
 return svg;
}
function rainBars(data){
 const svg=svgElement('svg',{viewBox:'0 0 700 120',role:'img','aria-label':'Daily precipitation in inches. Hollow baseline markers mean missing, circles mean trace amounts. Exact amounts follow in the table.'});
 const maximum=Math.max(.1,...data.rows.map(d=>d.rain??0)),width=625/data.totalDays;
 for(const d of data.rows){const x=50+(d.day-1)*625/(data.totalDays-1);const height=d.rain===null?0:d.rain/maximum*80;const mark=d.rainTrace?svgElement('circle',{cx:x,cy:100,r:3,fill:'var(--soil)'}):svgElement('rect',{x:x-width*.35,y:d.rain===null?96:100-height,width:width*.7,height:d.rain===null?4:Math.max(1,height),fill:d.rain===null?'none':'var(--green)',stroke:d.rain===null?'var(--muted)':'none'});const title=svgElement('title');title.textContent=`${d.date}: ${d.rain===null?'unknown':d.rainTrace?'trace':d.rain.toFixed(2)+' in'}`;mark.append(title);svg.append(mark);}
 const label=svgElement('text',{x:5,y:22,fill:'currentColor','font-size':11});label.textContent=maximum.toFixed(2)+' in';svg.append(label);return svg;
}
export function seasonWeather(dataset,{invalidation}={}){
 const section=el('section');section.className='decision-workbench weather-comparison';section.setAttribute('aria-label','Compare growing-season weather');
 section.append(el('h3','Is this season warmer at the station?'),el('p','Compare daily air temperatures at three Massachusetts airports. This archived snapshot is regional context; soil temperature and your garden’s frost pockets still need observation.'));
 const controls=el('div');controls.className='decision-controls';section.append(controls);
 const station=choice(controls,'Station',dataset.stations.map(s=>[s.id,s.name.replace(', MA US','')]),dataset.stations[0].id);
 const months=['January','February','March','April','May','June','July','August','September','October','November','December'];
 const latest=dataset.stations.flatMap(s=>s.days.map(d=>d.date)).sort().at(-1);
 const month=choice(controls,'Month',months.map((m,i)=>[i+1,m]),Number(latest.slice(5,7)));
 const mode=choice(controls,'View',[['daily','Daily temperatures'],['departure','Departure from normal'],['accumulated','Accumulated precipitation']],'daily');
 const output=el('div');output.setAttribute('aria-live','polite');section.append(output);
 const year=Number(latest.slice(0,4));
 function render(){const selected=dataset.stations.find(s=>s.id===station.value), d=compareSeasonWeather(selected,year,+month.value);output.replaceChildren();
  output.append(el('h4',`${months[+month.value-1]} ${year} versus the same dates in 2023–2025`));
  const delta=d.difference===null?'Not enough matched data':`${Math.abs(d.difference).toFixed(1)}°F ${d.difference<0?'cooler':'warmer'} on matched dates`;
  output.append(el('p',`${delta}. ${d.matchedDays} of ${d.totalDays} calendar days have valid high and low temperatures in all four years.`));
  output.append(el('p',`${d.observedDays} observed days in ${year}; ${d.freezeDays} of those had a station low at or below 32°F. Missing days are unknown. Latest valid station date: ${d.latestDate}.`));
  const events=loadGardenJournal().filter(e=>e.date.startsWith(`${year}-${String(month.value).padStart(2,'0')}`));
  const figure=el('figure');figure.className='weather-chart';figure.tabIndex=0;figure.setAttribute('aria-label','Temperature comparison chart; scroll horizontally on small screens');figure.append(chart(d,events,mode.value),el('figcaption',mode.value==='daily'?`Solid green: ${year}; dashed brown: 2023–2025 midpoint average; dotted: 1991–2020 normal midpoint. Triangles: station freezes. Dots: your garden records. Filled coverage squares: recorded; empty: missing.`:mode.value==='departure'?'Observed midpoint minus normal midpoint. This is not a comparison with an observed daily mean. Missing values leave gaps.':'Accumulation starts on day 1 and ends at the first missing observation. It never silently bridges missing rainfall. Trace amounts count as zero measurable inches.'));output.append(figure);const rainFigure=el('figure');rainFigure.className='weather-chart weather-rain';rainFigure.tabIndex=0;rainFigure.setAttribute('aria-label','Daily precipitation chart; scroll horizontally on small screens');rainFigure.append(rainBars(d),el('figcaption',`Daily precipitation · ${d.rainDays}/${d.totalDays} days recorded · ${d.rainObservedTotal.toFixed(2)} inches on recorded days only. Precipitation includes liquid-equivalent snow, not only rain. Hollow markers: missing; circles: trace.`));output.append(rainFigure);if(events.length){output.append(el('h4','Your observations alongside this weather'));for(const event of events)output.append(el('p',`${event.date} · ${event.crop||event.bed||'Garden'}: ${event.notes||event.type.replaceAll('_',' ')}`));output.append(el('p','Dots mark your records. A nearby weather event does not establish what caused a garden outcome.'));}
  const details=el('details');details.append(el('summary','View daily values and missing observations'));
  const wrap=el('div');wrap.className='table-wrap';wrap.tabIndex=0;wrap.setAttribute('role','region');wrap.setAttribute('aria-label','Daily temperature comparison');
  const table=el('table'),head=el('thead'),tr=el('tr');['Date',`${year} midpoint °F`,'2023–2025 midpoint °F',`${year} low °F`,'1991–2020 normal midpoint °F','Departure °F','Precipitation in','Accumulated in','Included in recent-years difference'].forEach(t=>{const th=el('th',t);th.scope='col';tr.append(th);});head.append(tr);table.append(head);const body=el('tbody');
  d.rows.forEach(row=>{const r=el('tr');[row.date,...[row.current,row.baseline,row.low,row.normal,row.departure].map(v=>v===null?'Unknown':v.toFixed(1)),row.rain===null?'Unknown':row.rainTrace?'Trace':row.rain.toFixed(2),row.rainAccumulated===null?'Unknown':row.rainAccumulated.toFixed(2),row.matched?'Yes':'No'].forEach(v=>r.append(el('td',v)));body.append(r);});table.append(body);wrap.append(table);details.append(wrap);output.append(details);
 }
 controls.addEventListener('change',render);for(const event of ['garden-records-changed','notebook-sync-status','storage'])globalThis.addEventListener(event,render);invalidation?.then(()=>{for(const event of ['garden-records-changed','notebook-sync-status','storage'])globalThis.removeEventListener(event,render);});render();
 section.append(el('p',`Retrieved ${dataset.retrievedAt.slice(0,10)}. Fixed snapshot, not a live feed. The daily midpoint is (maximum + minimum) ÷ 2, not an observed daily mean. Three prior years are not a 30-year climate normal. The overall difference uses only dates present in all four years; February 29 cannot match non-leap years.`));
 const p=el('p'),a=el('a','NOAA NCEI source query');a.href=dataset.sourceUrl;p.append(a,document.createTextNode(' · '));const download=el('button','Download comparison data');download.type='button';download.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(dataset,null,2)],{type:'application/json'}));const link=el('a');link.href=url;link.download='veggie-farm-noaa-weather-snapshot.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});p.append(download);section.append(p);if(dataset.additionalSources){const sources=el('details');sources.append(el('summary','Normals, precipitation and archive sources'));for(const source of dataset.additionalSources){const line=el('p'),link=el('a',source.label);link.href=source.url;line.append(link,document.createTextNode(` · retrieved ${source.retrievedAt.slice(0,10)} · SHA-256 ${source.sha256}`));sources.append(line);}section.append(sources);}
 const next=el('a','Check your soil temperature and a current forecast in Garden Today →');next.href='/tools/today';section.append(next);
 return section;
}
